// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StarterM.Models
{
    public partial class Order
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [StringLength(50)]
        public string RealName { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        public string Phone { get; set; }
        [Required]
        [StringLength(20)]
        public string Status { get; set; }
        [Column("MasterOrder_Id")]
        public int MasterOrderId { get; set; }
        [Column("Store_Id")]
        public int? StoreId { get; set; }
        [Column("Create_time", TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column("Update_time", TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
    }
}